export const Api = {  
  user: "/users",
  login: "/login",
  verify: "/verify/",
  search: "/search",
  category: "/categories",
  products: "/products",
  mongoProducts: "/mongoProducts",
  orders: "/orders",
  cart: "/carts",
  dashboard: "/dashboard",
  cartByUser: "/carts/user/",
  userPref: '/userPref',
  notification: '/notif',
};
