export const Api = {
  deleteUser: "/user/delete",
  user: "/users/",
  getRoles: "/users/roles",
  register: "/users",
  login: "/login",
  verify: "/verify/",
  search: "/search",
  category: "/categories",
  getMockRoles: "/mock/roles",
  mockRegister: "/mock/users",
  products: "/products",
  mongoProducts: "/mongoProducts",
  orders: "/orders",
  order: "/order",
  cart: "/carts",
};
