export const Api = {
  deleteUser: "/user/delete",
  user: "/users/",
  register: "/users",
  login: "/login",
  verify: "/verify/",
  search: "/search",
  category: "/categories",
  getMockRoles: "/mock/roles",
  mockRegister: "/mock/users",
  products: "/products",
  mongoProducts: "/mongoProducts",
  orders: "/orders",
  order: "/order",
  cart: "/carts",
  dashboard: "/dashboard",
  cartByUser: "/carts/user/",
  userPref: '/userPref',
  notification: '/notif',
};
