name: CI

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Start Docker Compose services
        run: docker-compose up -d

      - name: Clean database schema
        run: docker compose exec node migrate-down-all-test

      - name: Set up database schema
        run: docker compose exec node migrate-up-test

      - name: Run tests
        run: docker compose exec node npm test
